### ISSUE TITLE
External link https://djangopackages.org/grids/g/linters/ broken

### ISSUE THREAD

**Issue by hamishwillee** [djangopackages/djangopackages#1022] opened 2023-09-24 23:43 UTC
Just go to this list of Django aware linters: https://djangopackages.org/grids/g/linters/
This is the same URL you get to from search.

![image](https://github.com/djangopackages/djangopackages/assets/5368500/630c36a2-3785-4e0b-82e8-30194a34ff1b)

**Comment by ryancheley** [comment] 2023-09-26 12:21
this is a duplicate of #1021

**Closed** 2023-09-26 12:55 UTC
Labels: Duplicate

**Comment by jefftriplett** [comment] 2023-09-27 13:47
Thank you for the report. Everything is fixed now. 

I'm afraid my bus factor + four days of flu + my youngest having a minor procedure (they are fine) was the perfect storm for me not being around to see this.

**Comment by hamishwillee** [comment] 2023-09-27 21:03
Pleased to hear your youngest is well. No worries.
